#端口
server:
  port: 8084
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    min-spare-threads: 10
  connection-timeout: 5000ms
  servlet:
    context-path: /

http-path-img-url: http://112.74.180.75:8084
#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      minimum-idle: 10   # 保持连接的最小值
      maximum-pool-size: 20   # 可同时连接的最大连接数
      max-lifetime: 0      # 连接池中的连接的最长生命周期（毫秒）,数值 0 表示不限制
      connection-timeout: 60000   # 连接超时时间（毫秒）
  # jpa
  jpa:
    database: mysql
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: false
#原生日志
logging:
      level:
        root: info
        com.tcxn: warn
      file: log/blog-pro.log